addSbtPlugin("com.earldouglas" % "xsbt-web-plugin" % "2.1.0")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.6.1")
addSbtPlugin("org.ensime" % "sbt-ensime" % "1.0.0")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.3")
//addSbtPlugin("com.arpnetworking" % "sbt-typescript" % "0.2.1")
